---
# tasks file for configure-hardening
- include_tasks: services.yml
- include_tasks: kernel_param.yml
- include_tasks: banner.yml
- include_tasks: ufw.yml
- include_tasks: bios.yml
- include_tasks: i3.yml
# - include: ntp.yml
