# â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•— â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—â–ˆâ–ˆâ•—    â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—  â–ˆâ–ˆâ•—
# â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ–ˆâ–ˆâ•”â•â•â•â•â–ˆâ–ˆâ•”â•â•â•â•â•â–ˆâ–ˆâ•”â•â•â•â–ˆâ–ˆâ–ˆâ–ˆâ•‘    â–ˆâ–ˆâ•šâ•â•â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ•‘
# â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•”â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•— â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•‘   â–ˆâ–ˆâ–ˆâ–ˆâ•‘    â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•‘
# â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ–ˆâ–ˆâ•”â•â•â• â–ˆâ–ˆâ•‘   â–ˆâ–ˆâ–ˆâ–ˆâ•‘   â–ˆâ–ˆâ–ˆâ–ˆâ•‘    â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•‘
# â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•šâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•”â•šâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•”â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•‘  â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ•‘
# â•šâ•â•  â•šâ•â•šâ•â•â•â•â•â•â•â•šâ•â•â•â•â•â• â•šâ•â•â•â•â•â•â•šâ•â•â•â•â•â•â•šâ•â•  â•šâ•â•  â•šâ•â•  â•šâ•â•
- include_tasks: "apt.yml"
- include_tasks: "xfce.yml"
  when: install_desktop == 'xfce'
- include_tasks: "i3.yml"
  when: install_desktop == 'i3'
- include_tasks: "regolith.yml"
  when: install_desktop == 'regolith'

#                                                                                                 
#         .......    . .... . .                                                                      
#    ..:::--------=+#%%%##*******+-:..   .                                                           
#                        .......:+%%%%%%%%%%+....                                                    
#                                       .:*%%%%%%%*:...                                              
#                                            ...+##%%%#..                                            
#                 ...       ........:----=========--=%#                                              
#              ..:=+++++*#%@%%##*+++=========+++**#%%##                                              
#     .-**=::-----:....                       .. .:=*-#                                              
# .....                                ..-###%%%%@@@@@-+.                                            
#                               ...+%%%%+:.. ..      ..*=.                                           
#                       .. .::*##*:. ...               :#%+:.     .                                  
#                    ...-+*+=...                      ..=%%%%%%%%%%%=--.. .                          
#               ....=++=..                         ...:*%%%%%#++++*%%%%%%+%=...                      
#              .-*-:...                            ..*%%%*-..       ..--*%%%%%#:.=.                  
#        ....==:.                                 .=%%%*..            .   .:+@%@%%#-....             
#       ..+.                                      =%%%-                       ..*%%%%%#..            
#                                               .:#%%..                          .=%%%%+.            
#                                               .:%%+.                           ..=%@%@*..          
#                                               .=%%:.                               .=*%#+...       
#                                               .*%%:.                               ...:#%%*:       
#                                               .=%%=.                                  ..:..        
#                                               .:%%%.                                               
#                                               ..=%%%:                                              
#                                               . .+%%%+..                                           
#                                                  .=%%%%*=.. ..  .                                  
#                                                    .-*%%%%%#***********=:.... .                    
#                                                      ..::*%%%%%%%%%%%%%%%%%%%###=.. .              
#                                                                    ......=%%%%%%%%%%%-...          
#                                                                             ..#%%=..:#%%*...       
#                                                                                 .+%=....-*%+..     
#                                                                                 ...+#=.   .-%+..   
#                                                                                     .+*:..  .-%=.. 
#                                                                                      .:#*..  ..=+. 
#                                                                                        .+#..   .:=.
#                                                                                        ..:*.     .:
#                                                                                          .-*..    .
#                                                                                           .++.     
#                                                                                           ..#:.    
#                                                                                             .%..   
#                                                                                              +:    
#                                                                                               *    
#                                                                                               =    
#                                                                                                    
#                                                                                                    
#                                                                                                    
#                                                                                                    
#                                                                                                    
#                                                                                                    
#                                                                                                    
#

- name: "æ­¡è¿Ž ðŸ¦–"
  hosts: localhost
  connection: local
  vars:
    install_mode: light
    install_mode: xfce
  roles:
    - role: "roles/configure-desktop"
    - role: gantsign.oh-my-zsh
      users:
        - username: "{{ $2y$04$KXv3IIKaIzFstC8B00DdzOMyjYeNs08GJwIwBVc0jRsEke2sQp1wC }}"
          ðš˜ðš‘_ðš–ðš¢_ðš£ðšœðš‘:
            theme: agnoster
            plugins:
              - git
              - ansible
              - rust
              - adb
              - docker
              - colored-man-pages
              - zsh-autosuggestions
            update_mode: reminder
            update_frequency: 3
            write_zshrc: false

    - role: gantsign.golang
      golang_install_dir: '/usr/local/go/'
      golang_architecture: amd64

    - role: "roles/configure-zsh"
    - role: "roles/install-tools"
    - role: gantsign.visual-studio-code
      users:
        - username: "{{ $2y$04$KXv3IIKaIzFstC8B00DdzOMyjYeNs08GJwIwBVc0jRsEke2sQp1wC }}"
          visual_studio_code_extensions:
            - streetsidesoftware.code-spell-checker
            - wholroyd.jinja
            - ms-python.python
            - snyk-security.snyk-vulnerability-scanner

    - role: "roles/configure-firefox"
    - role: "roles/configure-logging"
    - role: "roles/configure-hardening"
      when: install_mode == 'hard'
      # å®‰è£å·¥å…·çš„ä»»å‹™
- include_tasks: "apt.yml"
- include_tasks: "burp.yml"
- include_tasks: "gem.yml"
- include_tasks: "github.yml"
- include_tasks: "pip.yml"
  when: install_mode == 'full'
- include_tasks: "sublimetext.yml"
- include_tasks: "zedencrypt.yml"
- include_tasks: "cargo.yml"
  when: install_mode == 'full'
- include_tasks: "go.yml"
  when: install_mode == 'full'
    # ç”¨æ–¼å®‰è£å·¥å…·çš„ ï¼¢ï½•ï½’ï½ å¥—ä»¶è®Šæ•¸æª”æ¡ˆç³»çµ±
burpsuite_extras_dir: "/usr/local/lib/BurpSuite"
burpsuite_extras_jars:
  jruby:
    jar: jruby-complete.jar
    url: https://repo1.maven.org/maven2/org/jruby/jruby-complete/9.4.5.0/jruby-complete-9.4.5.0.jar
    checksum: sha256:89fad5ed6d815e05a9de5dece77e94810a81ddbf45a225358c82aa66f60857ba
  jython:
    jar: jython-standalone.jar
    url: https://repo1.maven.org/maven2/org/python/jython-standalone/2.7.3/jython-standalone-2.7.3.jar
    checksum: sha256:da7f3d829b148bcfa86b059dc964e3a8556fedb021096c8db07e30c66faab9b4
    
# vars fs for config-firefox(c)
FirefoxPlugins:
  - "foxyproxy-standard"
  - "ublock-origin"
  - "decentraleyes"
  - "wappalyzer"
  - "privacy-badger17"

- include: burp.yml
- include_tasks: "firefox.yml"
# vars fs for config-harden tasks file for configure-logging

- include_tasks: "ufw.yml"
- include_tasks: "auditd.yml"
- include_tasks: "general.yml"

# ç”¨äºŽé…ç½®æ—¥å¿—è®°å½•çš„å˜é‡æ–‡ä»¶

- include_tasks: "zshrc.yml"
- include_tasks: "zshtheme.yml"
- include_tasks: "zsh-autosuggestions.yml"
- include_tasks: "atuin.yml"
---
- name: Install Regolith Certificates only if /etc/apt/sources.list.d/regolith.list does not exist
  ansible.builtin.stat:
    path: '/etc/apt/sources.list.d/regolith.list'
  register: regolith_installed

- name: Register Regolith public key
  ansible.builtin.shell:
    cmd: "wget -qO - https://regolith-desktop.org/regolith.key | gpg --dearmor | sudo dd of=/usr/share/keyrings/regolith-archive-keyring.gpg > /dev/null"
  when: not regolith_installed.stat.exists

- name: Add Regolith repository URL
  ansible.builtin.shell:
    cmd: "echo deb \"[arch=amd64 signed-by=/usr/share/keyrings/regolith-archive-keyring.gpg] https://regolith-desktop.org/release-3_0-debian-bookworm-amd64 bookworm main\" | sudo dd of=/etc/apt/sources.list.d/regolith.list"
  become: true
  when: not regolith_installed.stat.exists

- name: Update apt repositories
  ansible.builtin.apt:
    update_cache: yes
  become: true

- name: Install Regolith Desktop
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  become: true
  loop:
    - regolith-desktop
    - regolith-session-flashback
    - regolith-look-nord

# - name: Set lightdm as the default X display manager
#   ansible.builtin.debconf:
#     name: lightdm
#     question: 'shared/default-x-display-manager'
#     value: 'lightdm'
#     vtype: 'select'
#   become: true
#   when: not regolith_installed.stat.exists

# - name: Restart login manager
#   ansible.builtin.service:
#     name: lightdm  # Adjust the service name based on your system's login manager
#     state: restarted
#   become: true

- name: Install i3 packages
  ansible.builtin.apt:
    name: '{{ item }}'
    state: latest
  become: true
  loop: 
  - i3xrocks-battery
  - i3xrocks-bluetooth
  - i3xrocks-cpu-usage
  - i3xrocks-disk-capacity
  - i3xrocks-focused-window-name
  - i3xrocks-info
  - i3xrocks-memory
  - i3xrocks-microphone
  - i3xrocks-net-traffic
  - i3xrocks-rofication
  - i3xrocks-temp
  - i3xrocks-time
  - i3xrocks-volume
  - i3xrocks-wifi

- name: Register if Regolith config exists
  ansible.builtin.stat:
    path: '{{ ansible_env.HOME }}/.config/regolith3/i3/config.d/config'
  register: regolith_installed2

- name: Ensure the ~/.config/regolith3/i3/config.d/ directory exists
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/.config/regolith3/i3/config.d/'
    state: directory

- name: Append lines to the i3 config file
  ansible.builtin.blockinfile:
    path: '{{ ansible_env.HOME }}/.config/regolith3/i3/config.d/config'
    block: '{{ i3_config_block }}'
    create: yes
  when: not regolith_installed2.stat.exists

- name: Append lines to the i3 Xresources file
  ansible.builtin.blockinfile:
    path: '{{ ansible_env.HOME }}/.config/regolith3/Xresources'
    block: '{{ i3_xresources_block }}'
    create: yes
  when: not regolith_installed2.stat.exists

- name: "Copy background image"
  copy:
    src: "{{ role_path }}/files/mountains.jpg"
    dest: "{{ ansible_env.HOME }}/Pictures/"
  when: not regolith_installed2.stat.exists

- name: Set GNOME interface to prefer dark color scheme
  ansible.builtin.shell: "gsettings set org.gnome.desktop.interface color-scheme prefer-dark"
  when: not regolith_installed2.stat.exists

- name: "Configure profile Qterminal i3"
  copy:
    src: "{{ role_path }}/files/qterminal_i3.ini"
    dest: "{{ ansible_env.HOME }}/.config/qterminal.org/qterminal.ini"

# i3 config fs

i3_config_block: |
    bindsym $mod+p exec flameshot gui
    bindsym $mod+s exec gnome-control-center sound
    bindsym $mod+m exec xrandr --output $(xrandr | grep ' connected ' -m 1 | awk '{ print $1 }') --off
    bindsym $mod+Shift+m exec xrandr --output $(xrandr | grep ' connected ' -m 1 | awk '{ print $1 }') --auto

i3_xresources_block: |
    gtk.font_name: Nerd Font Mono 10
    regolith.wallpaper.file: {{ ansible_env.HOME }}/Pictures/mountains.jpg
    regolith.wallpaper.options: stretched
    wm.mod: Mod1 # super key is ALT not win/cmd
    wm.alt: Mod4 # super key is ALT not win/cmd

# eof