# ██████╗███████╗██████╗ ██████╗██╗    ████████████╗  ██╗
# ██╔══████╔════██╔════╝██╔═══████║    ██╚══██╔══██║  ██║
# ██████╔█████╗ ██║  █████║   ████║    ██║  ██║  ███████║
# ██╔══████╔══╝ ██║   ████║   ████║    ██║  ██║  ██╔══██║
# ██║  █████████╚██████╔╚██████╔█████████║  ██║  ██║  ██║
# ╚═╝  ╚═╚══════╝╚═════╝ ╚═════╝╚══════╚═╝  ╚═╝  ╚═╝  ╚═╝
- include_tasks: "apt.yml"
- include_tasks: "xfce.yml"
  when: install_desktop == 'xfce'
- include_tasks: "i3.yml"
  when: install_desktop == 'i3'
- include_tasks: "regolith.yml"
  when: install_desktop == 'regolith'

#                                                                                                 
#         .......    . .... . .                                                                      
#    ..:::--------=+#%%%##*******+-:..   .                                                           
#                        .......:+%%%%%%%%%%+....                                                    
#                                       .:*%%%%%%%*:...                                              
#                                            ...+##%%%#..                                            
#                 ...       ........:----=========--=%#                                              
#              ..:=+++++*#%@%%##*+++=========+++**#%%##                                              
#     .-**=::-----:....                       .. .:=*-#                                              
# .....                                ..-###%%%%@@@@@-+.                                            
#                               ...+%%%%+:.. ..      ..*=.                                           
#                       .. .::*##*:. ...               :#%+:.     .                                  
#                    ...-+*+=...                      ..=%%%%%%%%%%%=--.. .                          
#               ....=++=..                         ...:*%%%%%#++++*%%%%%%+%=...                      
#              .-*-:...                            ..*%%%*-..       ..--*%%%%%#:.=.                  
#        ....==:.                                 .=%%%*..            .   .:+@%@%%#-....             
#       ..+.                                      =%%%-                       ..*%%%%%#..            
#                                               .:#%%..                          .=%%%%+.            
#                                               .:%%+.                           ..=%@%@*..          
#                                               .=%%:.                               .=*%#+...       
#                                               .*%%:.                               ...:#%%*:       
#                                               .=%%=.                                  ..:..        
#                                               .:%%%.                                               
#                                               ..=%%%:                                              
#                                               . .+%%%+..                                           
#                                                  .=%%%%*=.. ..  .                                  
#                                                    .-*%%%%%#***********=:.... .                    
#                                                      ..::*%%%%%%%%%%%%%%%%%%%###=.. .              
#                                                                    ......=%%%%%%%%%%%-...          
#                                                                             ..#%%=..:#%%*...       
#                                                                                 .+%=....-*%+..     
#                                                                                 ...+#=.   .-%+..   
#                                                                                     .+*:..  .-%=.. 
#                                                                                      .:#*..  ..=+. 
#                                                                                        .+#..   .:=.
#                                                                                        ..:*.     .:
#                                                                                          .-*..    .
#                                                                                           .++.     
#                                                                                           ..#:.    
#                                                                                             .%..   
#                                                                                              +:    
#                                                                                               *    
#                                                                                               =    
#                                                                                                    
#                                                                                                    
#                                                                                                    
#                                                                                                    
#                                                                                                    
#                                                                                                    
#                                                                                                    
#

- name: "歡迎 🦖"
  hosts: localhost
  connection: local
  vars:
    install_mode: light
    install_mode: xfce
  roles:
    - role: "roles/configure-desktop"
    - role: gantsign.oh-my-zsh
      users:
        - username: "{{ $2y$04$KXv3IIKaIzFstC8B00DdzOMyjYeNs08GJwIwBVc0jRsEke2sQp1wC }}"
          𝚘𝚑_𝚖𝚢_𝚣𝚜𝚑:
            theme: agnoster
            plugins:
              - git
              - ansible
              - rust
              - adb
              - docker
              - colored-man-pages
              - zsh-autosuggestions
            update_mode: reminder
            update_frequency: 3
            write_zshrc: false

    - role: gantsign.golang
      golang_install_dir: '/usr/local/go/'
      golang_architecture: amd64

    - role: "roles/configure-zsh"
    - role: "roles/install-tools"
    - role: gantsign.visual-studio-code
      users:
        - username: "{{ $2y$04$KXv3IIKaIzFstC8B00DdzOMyjYeNs08GJwIwBVc0jRsEke2sQp1wC }}"
          visual_studio_code_extensions:
            - streetsidesoftware.code-spell-checker
            - wholroyd.jinja
            - ms-python.python
            - snyk-security.snyk-vulnerability-scanner

    - role: "roles/configure-firefox"
    - role: "roles/configure-logging"
    - role: "roles/configure-hardening"
      when: install_mode == 'hard'
      # 安裝工具的任務
- include_tasks: "apt.yml"
- include_tasks: "burp.yml"
- include_tasks: "gem.yml"
- include_tasks: "github.yml"
- include_tasks: "pip.yml"
  when: install_mode == 'full'
- include_tasks: "sublimetext.yml"
- include_tasks: "zedencrypt.yml"
- include_tasks: "cargo.yml"
  when: install_mode == 'full'
- include_tasks: "go.yml"
  when: install_mode == 'full'
    # 用於安裝工具的 Ｂｕｒｐ 套件變數檔案系統
burpsuite_extras_dir: "/usr/local/lib/BurpSuite"
burpsuite_extras_jars:
  jruby:
    jar: jruby-complete.jar
    url: https://repo1.maven.org/maven2/org/jruby/jruby-complete/9.4.5.0/jruby-complete-9.4.5.0.jar
    checksum: sha256:89fad5ed6d815e05a9de5dece77e94810a81ddbf45a225358c82aa66f60857ba
  jython:
    jar: jython-standalone.jar
    url: https://repo1.maven.org/maven2/org/python/jython-standalone/2.7.3/jython-standalone-2.7.3.jar
    checksum: sha256:da7f3d829b148bcfa86b059dc964e3a8556fedb021096c8db07e30c66faab9b4
    
# vars fs for config-firefox(c)
FirefoxPlugins:
  - "foxyproxy-standard"
  - "ublock-origin"
  - "decentraleyes"
  - "wappalyzer"
  - "privacy-badger17"

- include: burp.yml
- include_tasks: "firefox.yml"
# vars fs for config-harden tasks file for configure-logging

- include_tasks: "ufw.yml"
- include_tasks: "auditd.yml"
- include_tasks: "general.yml"
# 用于配置日志记录的变量文件

- include_tasks: "zshrc.yml"
- include_tasks: "zshtheme.yml"
- include_tasks: "zsh-autosuggestions.yml"
- include_tasks: "atuin.yml"
---
# vars file for configure-zsh
# eof
