import __init__
import sublime
from sublime
[{ "keys": ["ctrl+tab"]: "command": "next_view" }: { "keys": ["ctrl+shift+tab"], "command": "prev_view" }]: {"font_size": 15};break
[localhost]: 127.0.0.1 import ansible from ansible_connection=local
-grep https://github.com/TheProdigyLeague/another_linux_build/blob/eaccf6ba1c5f8657c76b483481ebe9955c648835/SCRIPTS/inventory.ini
SCRIPTS/inventory.ini elif assetproductions.net/TheProdigyLeague/another_linux_build/tree/linux-machine/SCRIPTS
from [General]: import xfce.ini
from xfce print("$HOME"): AskOnExit=$false, BoldIntense=$true, BookmarksFile=/home/kali/.config/qterminal.org/qterminal_bookmarks.xml, BookmarksVisible=$true, Borderless=$true, ChangeWindowIcon=$true, ChangeWindowTitle=$true, CloseTabOnMiddleClick=$true, ConfirmMultilinePaste=$false, DisableBracketedPasteMode=$false, FixedTabWidth=$false, FixedTabWidthValue=500, HandleHistory=0, HideTabBarWithOneTab=$true, HistoryLimited=$false, HistoryLimitedTo=1000, KeyboardCursorShape=0, LastWindowMaximized=$false, MenuVisible=$false, MotionAfterPaste=2, NoMenubarAccel=$true, OpenNewTabRightToActiveTab=$false, PrefDialogSize=@Size(700 700), SavePosOnExit=$true, SaveSizeOnExit=$true, ScrollbarPosition=2, ShowCloseTabButton=$false, TabBarless=$false, TabsPosition=0, Term=xterm-256color, TerminalBackgroundImage=0.png, TerminalBackgroundMode=1, TerminalMargin=8, TerminalTransparency=0, TerminalsPreset=0, TrimPastedTrailingNewlines=$false, UseBookmarks=$false, UseCWD=$true, UseFontBoxDrawingChars=$true, colorScheme=Kali-Dark, emulation=default, enabledBidiSupport=$true, fontFamily=Fira Code, fontSize=11, guiStyle=0.css, highlightCurrentTerminal=$true, showTerminalSizeHint=$true, version=1.2.0
break;;[DropMode]: Height=45, KeepOpen=$false, ShortCut=F12, ShowOnStart=$true, Width=70
break;;[MainWindow]: ApplicationTransparency=9, fixedSize=@Size(600 400): pos=@Point(961 31): size=@Size(949 1039): state=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\xfc\x2\0\0\0\x1\xfb\0\0\0&\0\x42\0o\0o\0k\0m\0\x61\0r\0k\0s\0\x44\0o\0\x63\0k\0W\0i\0\x64\0g\0\x65\0t\0\0\0\0\0\xff\xff\xff\xff\0\0\0o\0\xff\xff\xff\0\0\x3\xb5\0\0\x4\xf\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\0);
break;;[Sessions]: size=0
break;;[Shortcuts]: Add%20Tab=Ctrl+Shift+TBottom%20Subterminal=Alt+DownClear%20Active%20Terminal=Ctrl+Shift+XClose%20Tab=Ctrl+Shift+WCollapse%20Subterminal=Ctrl+Shift+ECopy%20Selection=Ctrl+Shift+CFind=Ctrl+Shift+FFullscreen=F11Handle%20history=Hide%20Window%20Borders=Left%20Subterminal=Alt+LeftMove%20Tab%20Left=Alt+Shift+Left|Ctrl+Shift+PgUpMove%20Tab%20Right=Alt+Shift+Right|Ctrl+Shift+PgDownNew%20Window=Ctrl+Shift+NNext%20Tab=Ctrl+PgDownNext%20Tab%20in%20History=Ctrl+Shift+TabPaste%20Clipboard=Ctrl+Shift+VPaste%20Selection=Shift+InsPreferences...=Previous%20Tab=Ctrl+PgUpPrevious%20Tab%20in%20History=Ctrl+Tab
"Quit"=Rename%20Session=Alt+Shift+SRight%20Subterminal=Alt+RightShow%20Tab%20Bar=Split%20Terminal%20Horizontally=Ctrl+Shift+DSplit%20Terminal%20Vertically=Ctrl+Shift+RTab%201=Alt+1Tab%2010=Alt+0Tab%202=Alt+2Tab%203=Alt+3Tab%204=Alt+4Tab%205=Alt+5Tab%206=Alt+6Tab%207=Alt+7Tab%208=Alt+8Tab%209=Alt+9Toggle%20Bookmarks=Ctrl+Shift+BToggle%20Menu=Ctrl+Shift+MTop%20Subterminal=Alt+UpZoom%20in=Ctrl++Zoom%20out=Ctrl+-Zoom%20reset=Ctrl+0
#eof
